# Site settings
title: 107 Blog
SEOTitle: 107的博客 | 107 Blog
header-img: img/home-bg.jpg
email: 57672737@qq.com
description: "May Your Heart Be The Map"
keyword: ""
url: "http://tomens.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:   
#github_username:    tomens  
#zhihu_username:     
#twitter_username:  
#facebook_username:  



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: Bebop.C
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: d59d067e8500ddc9aafddb11c2cdc1ab
# Google Analytics
ga_track_id: 'UA-75516959-1'            # Format: UA-xxxxxx-xx
ga_domain: tomens.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "不忘初心，方得始终。"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#   {
 #       title: "Bebop.C Blog",
 #       href: "http://playingfingers.com"
#    }
 #   ,
 #   {
#        title: "Spike Spiegel",
 #       href: "#"
#    },{
#        title: "Jet Black",
#        href: "#"
 #   },{
 #       title: "Faye Valentine",
 #       href: "#"
#    },{
#        title: "Ein",
#        href: "#"
#    }
#]
